const Sequelize = require('sequelize')
const db = require('../db')

const Company = db.define('company', {
  Company_Name: {type: Sequelize.STRING},
  Ticker_Symbol: {type: Sequelize.STRING},
  Beta: {type: Sequelize.STRING},
  Stock_Price: {type: Sequelize.DECIMAL},
  Volume: {type: Sequelize.DECIMAL},
  Current_EPS: {type: Sequelize.DECIMAL},
  EPS_Trail_12_Mo: {type: Sequelize.DECIMAL},
  Current_PE_Ratio: {type: Sequelize.DECIMAL},
  Relative_PE_Ratio: {type: Sequelize.DECIMAL},
  Median_PE: {type: Sequelize.DECIMAL},
  Earnings_Yield_Trail_12_Mo: {type: Sequelize.DECIMAL},
  High_Price_52_Week: {type: Sequelize.DECIMAL},
  Low_Price_52_Week: {type: Sequelize.DECIMAL},
  Indicated_Annual_Dividend: {type: Sequelize.DECIMAL},
  Divd_Yield: {type: Sequelize.DECIMAL},
  Market_Cap_: {type: Sequelize.DECIMAL},
  Reported_Annual_Sales: {type: Sequelize.DECIMAL},
  Gross_Income: {type: Sequelize.DECIMAL},
  Income_Before_Taxes: {type: Sequelize.DECIMAL},
  Net_Income: {type: Sequelize.DECIMAL},
  Profit_Margin: {type: Sequelize.DECIMAL},
  Cash: {type: Sequelize.DECIMAL},
  Total_Current_Liabilities: {type: Sequelize.DECIMAL},
  Working_Capital: {type: Sequelize.DECIMAL},
  Long_Term_Debt: {type: Sequelize.DECIMAL},
  Shareholders_Equity: {type: Sequelize.DECIMAL},
  Total_Capital: {type: Sequelize.DECIMAL},
  Common_Shares_Outstanding: {type: Sequelize.DECIMAL},
  Free_Cash_Flow: {type: Sequelize.DECIMAL},
  Return_on_Total_Assets: {type: Sequelize.DECIMAL},
  Dividend_Payout: {type: Sequelize.DECIMAL},
  Sales_per_share: {type: Sequelize.DECIMAL},
  Cash_Flow_per_share: {type: Sequelize.DECIMAL},
  Basic_Earn_PSh: {type: Sequelize.DECIMAL},
  Divds_Declared_per_share: {type: Sequelize.DECIMAL},
  PriceSales_Ratio: {type: Sequelize.DECIMAL},
  Avg_Annual_Dividend_Yield: {type: Sequelize.DECIMAL},
  Price_To_Book_Value: {type: Sequelize.DECIMAL},
  Sales_Growth_5_Year: {type: Sequelize.DECIMAL},
  Cash_Flow_Growth_5_Year: {type: Sequelize.DECIMAL},
  EPS_Growth_5_Year: {type: Sequelize.DECIMAL},
  Dividend_Growth_5_Year: {type: Sequelize.DECIMAL},
  Book_Value_Growth_5_Year: {type: Sequelize.DECIMAL},
  Total_Return_YTD: {type: Sequelize.DECIMAL},
  Total_Return_5_Year: {type: Sequelize.DECIMAL},
  Total_Return_2017: {type: Sequelize.DECIMAL},
  Total_Return_2016: {type: Sequelize.DECIMAL},
  Total_Return_2015: {type: Sequelize.DECIMAL},
  Total_Return_2014: {type: Sequelize.DECIMAL},
  Total_Return_2013: {type: Sequelize.DECIMAL},
  Total_Return_2012: {type: Sequelize.DECIMAL},
  Total_Return_2011: {type: Sequelize.DECIMAL},
  Total_Return_2010: {type: Sequelize.DECIMAL},
  Total_Return_2009: {type: Sequelize.DECIMAL},
  Total_Return_2008: {type: Sequelize.DECIMAL}
})

module.exports = Company
